/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { YAMORegistry__factory } from "./YAMORegistry__factory";
export { YAMORegistryV2__factory } from "./YAMORegistryV2__factory";
